### ISSUE TITLE
max iterations fuzzy-c-means

### ISSUE THREAD

**Issue by TerradasExatas** [omadson/omadson#2]
olá, me chamo Dennis e estou usando sua biblioteca fuzzy-c-means.
Estou com dificuldades em ajustas as opções do algoritmo, como max-iterations e seed.
Olhei o arquico CLI.md mas ainda não fui capaz de ajustar essas opções, poderia postar os comandos alternativos á:

fcm = FCM(n_clusters=3)
fcm.fit(X)

ou mesmo um outro exemplo usando essas opções?

muito obrigado

**Comment by omadson** [comment]
Olá, @TerradasExatas. Poderia criar essa mesma issue no [repositório do fuzzy-c-means](https://github.com/omadson/fuzzy-c-means)?

**Comment by omadson** [comment]
Olá, @TerradasExatas. Para utilizar o número máximo de iterações e semente, basta usar os argumentos `max_iter` e `random_state`. Um exemplo é:


```Python
fcm = FCM(n_clusters=3, random_state=42, max_iter=1000)
fcm.fit(X)
```

Tente com o código acima e me envie alguma dúvida que restar.
